export type AtsProvider = 'greenhouse' | 'lever';

export interface CompanyRegistryEntry {
  name: string;
  ats: AtsProvider;
  slug: string;
}

export const COMPANY_REGISTRY: CompanyRegistryEntry[] = [
  { name: 'Google', ats: 'greenhouse', slug: 'google' },
  { name: 'Microsoft', ats: 'greenhouse', slug: 'microsoft' },
  { name: 'Amazon', ats: 'greenhouse', slug: 'amazon' },
  { name: 'Meta', ats: 'greenhouse', slug: 'meta' },
  { name: 'Apple', ats: 'greenhouse', slug: 'apple' },
  { name: 'Nvidia', ats: 'greenhouse', slug: 'nvidia' },
  { name: 'Stripe', ats: 'greenhouse', slug: 'stripe' },
  { name: 'Airbnb', ats: 'greenhouse', slug: 'airbnb' },
  { name: 'Uber', ats: 'greenhouse', slug: 'uber' },
  { name: 'Databricks', ats: 'greenhouse', slug: 'databricks' },
  { name: 'Snowflake', ats: 'greenhouse', slug: 'snowflake' },
  { name: 'Atlassian', ats: 'greenhouse', slug: 'atlassian' },
  { name: 'Adobe', ats: 'greenhouse', slug: 'adobe' },
  { name: 'Salesforce', ats: 'greenhouse', slug: 'salesforce' },
  { name: 'Cisco', ats: 'greenhouse', slug: 'cisco' },
  { name: 'Oracle', ats: 'greenhouse', slug: 'oracle' },
  { name: 'AMD', ats: 'greenhouse', slug: 'amd' },
  { name: 'Intel', ats: 'greenhouse', slug: 'intel' },
  { name: 'Palantir', ats: 'greenhouse', slug: 'palantir' },
  { name: 'Rippling', ats: 'lever', slug: 'rippling' },
  { name: 'Notion', ats: 'lever', slug: 'notion' },
  { name: 'Figma', ats: 'greenhouse', slug: 'figma' },
  { name: 'Linear', ats: 'lever', slug: 'linear' },
  { name: 'OpenAI', ats: 'greenhouse', slug: 'openai' },
  { name: 'Anthropic', ats: 'greenhouse', slug: 'anthropic' },
  { name: 'Coinbase', ats: 'greenhouse', slug: 'coinbase' },
  { name: 'DoorDash', ats: 'greenhouse', slug: 'doordash' },
  { name: 'Instacart', ats: 'lever', slug: 'instacart' },
  { name: 'TikTok', ats: 'lever', slug: 'tiktok' },
  { name: 'Snap', ats: 'greenhouse', slug: 'snap' },
  { name: 'LinkedIn', ats: 'greenhouse', slug: 'linkedin' },
  { name: 'Shopify', ats: 'lever', slug: 'shopify' },
  { name: 'Roblox', ats: 'greenhouse', slug: 'roblox' },
  { name: 'Discord', ats: 'lever', slug: 'discord' },
  { name: 'Duolingo', ats: 'greenhouse', slug: 'duolingo' },
  { name: 'Zendesk', ats: 'greenhouse', slug: 'zendesk' },
  { name: 'Twilio', ats: 'greenhouse', slug: 'twilio' },
  { name: 'Box', ats: 'greenhouse', slug: 'box' },
  { name: 'Canva', ats: 'lever', slug: 'canva' },
  { name: 'Asana', ats: 'greenhouse', slug: 'asana' },
  { name: 'MongoDB', ats: 'greenhouse', slug: 'mongodb' },
  { name: 'HashiCorp', ats: 'greenhouse', slug: 'hashicorp' },
  { name: 'Reddit', ats: 'lever', slug: 'reddit' },
  { name: 'ServiceNow', ats: 'greenhouse', slug: 'servicenow' },
  { name: 'Cloudflare', ats: 'greenhouse', slug: 'cloudflare' },
  { name: 'Netflix', ats: 'greenhouse', slug: 'netflix' },
  { name: 'GitHub', ats: 'greenhouse', slug: 'github' },
  { name: 'Docker', ats: 'lever', slug: 'docker' },
  { name: 'Carta', ats: 'greenhouse', slug: 'carta' },
  { name: 'Brex', ats: 'lever', slug: 'brex' },
  { name: 'Scale AI', ats: 'greenhouse', slug: 'scaleai' },
  { name: 'Waymo', ats: 'greenhouse', slug: 'waymo' },
  { name: 'Ramp', ats: 'lever', slug: 'ramp' },
  { name: 'Replit', ats: 'lever', slug: 'replit' },
  { name: 'Hightouch', ats: 'greenhouse', slug: 'hightouch' },
  { name: 'Datadog', ats: 'greenhouse', slug: 'datadog' },
  { name: 'Perplexity', ats: 'greenhouse', slug: 'perplexity' },
  { name: 'Okta', ats: 'greenhouse', slug: 'okta' },
  { name: 'Fivetran', ats: 'lever', slug: 'fivetran' },
  { name: 'Airtable', ats: 'greenhouse', slug: 'airtable' },
  { name: 'Coda', ats: 'lever', slug: 'coda' },
  { name: 'Gusto', ats: 'greenhouse', slug: 'gusto' },
  { name: 'Tandem', ats: 'lever', slug: 'tandem' },
  { name: 'Joby Aviation', ats: 'greenhouse', slug: 'jobyaviation' },
  { name: 'Zip', ats: 'lever', slug: 'zip' },
];

export function getCompanyRegistryBySlug(slug: string) {
  return COMPANY_REGISTRY.find((company) => company.slug === slug);
}